### PR TITLE
[EVNT-505] Update account_id to org_id in events filter

### PR DESCRIPTION
**Pull request by CodeHeeler**

### CODE REVIEW

**Comment by CodeHeeler** [comment]
Leaving column title in table as "Account" for now pending discussion.  Not sure if it's important to rename or explain in tooltip what specific id is referred to here or not, or to leave it be as an expected column name for the best user experience.

**Comment by petrblaho** [comment]
Nice.... can we get https://github.com/RedHatInsights/eventing-splunk-app/tree/main/examples updated too?

**Review by fellipeh — APPROVED** [review]
LGTM

**Review by petrblaho — APPROVED** [review]
LGTM!

**Comment by vkrizan** [comment]
Didn't we wanted to keep two filters, one for account number an the other for org id? @sthirugn ?

**Comment by CodeHeeler** [comment]
> Didn't we wanted to keep two filters, one for account number an the other for org id? @sthirugn ?

Yes, I think the original plan was to, like Notifications, support both, but I'm not sure how to do an if/else on the filter and presumably need additional columns for that, so I was thinking we could just test this out and then not push to prod until all the other apps have completed their migration to use org_id.

**Comment by sthirugn** [comment]
> Didn't we wanted to keep two filters, one for account number an the other for org id? @sthirugn ?

Yes, I think we like to show both the filters as consoledot UI is going to show both I think, but we are still waiting to hear about the platform's directions. Let's not merge this now.

**Comment by CodeHeeler** [comment]
> > Didn't we wanted to keep two filters, one for account number an the other for org id? @sthirugn ?
> 
> Yes, I think we like to show both the filters as consoledot UI is going to show both I think, but we are still waiting to hear about the platform's directions. Let's not merge this now.

Yeah, agreed, we're definitely not merging this right now, but have you seen any mocks to this effect for showing both?

**Comment by sthirugn** [comment]
nope I havent seen any mocks yet, lets wait

**Comment by vkrizan** [comment]
Closing as this is not required.

**Pull request closed without merging**
